// Auto-generated by build.js — do not edit directly
var CONTENT_EN = {
  "nav": {
    "whatWeDo": "What",
    "ourStory": "Who",
    "connect": "Connect"
  },
  "hero": {
    "tagline": "Built for Those Who Build",
    "descHeader": "Method Index integrates a wide array of disciplines to our Consulting Services.",
    "descBody": "Rabih Sater's long experience, healthy track record and the successful brands we've worked with, can provide new or existing business consulting in Business Concept Development, Identity Design, Business Operations, Brand Experience and Strategical Marketing. Demographics, Geography, Area Development and Financial Analysis can also be part of an extensive consulting study to get your business up and operating successfully.",
    "backgroundImage": "assets/hero-bg.png"
  },
  "mission": {
    "quote": "Our mission<br><em>is your success.</em>",
    "sub": "We do not adhere to the belief that the unique needs of our clients can be satisfied with a pre-programmed approach."
  },
  "whatIntro": {
    "heading": "Our services are customized to the needs and specifications of each client – we do not adhere to the belief that the unique needs of our clients can be satisfied with a pre-programmed approach.",
    "body": "This means that we spend a lot of time in the field understanding what makes each business or product micro-market unique. We also get to know people at all levels in order to completely understand their priorities, processes, perceptions and concerns. In addition, we bring a rigorous financial methodology to our work. Every recommendation is evaluated in terms of its highest value and return on your investment. And we know how important your investment is."
  },
  "services": {
    "label": "What We Do",
    "tagline": "Five disciplines.<br>One integrated approach.",
    "names": [
      "Concept Development",
      "Identity Design",
      "Business Operations",
      "Brand Experience",
      "Marketing Strategy"
    ],
    "descs": [
      "We identify your core market, define your offering, and build the strategic foundation every successful brand requires.",
      "Brand language, visual systems, and consumer positioning crafted to command attention and hold it.",
      "Management strategy, HR development, and operational architecture built to scale without compromise.",
      "Interior and exterior environments, social presence, and every touchpoint that defines how your brand is felt.",
      "Local market intelligence, lifestyle positioning, and social campaigns that reach the right people precisely."
    ],
    "marquee": "Concept Development &nbsp;·&nbsp; Identity Design &nbsp;·&nbsp; Business Operations &nbsp;·&nbsp; Brand Experience &nbsp;·&nbsp; Marketing Strategy &nbsp;·&nbsp; Concept Development &nbsp;·&nbsp; Identity Design &nbsp;·&nbsp; Business Operations &nbsp;·&nbsp; Brand Experience &nbsp;·&nbsp; Marketing Strategy &nbsp;·&nbsp; "
  },
  "about": {
    "label": "Who",
    "heading": "Keep Complexity,<br><em>To Accessibility.</em>",
    "body": "Born in the Ivory Coast, Rabih Sater developed a taste for business at an early age. As a young boy, he moved to the United States when work and civil strife threatened his family. His father's business in car repair and gas stations put him to work at the age of 5. The family work ethic and drive to succeed in pursuing the American Dream was never left untaught. His father taught him a great deal of all the ins and outs of operating a small business. Eventually, as the family business grew, Rabih's role managing and operating a collection of retail and real estate businesses with over 350 employees under his direction at the age of 24. He was able to operate and develop, fuel stations, retail centers, fast food facilities and modernize operations all within his family business and to global industry clients alike. While in college, he was heavily influenced with creative inspiration thru hospitality legend Ian Schrager's attention to detail, risk taking and aesthetics. This influence brought a realization to how many potential brands lay afloat in the market place, but lack the details and direction to be national or global successes. Method Index was created as the connection to the consumer, a multitude of Rabih's ideas that can manifest into successful realities.",
    "quote": "For long as I remember, I've always dreamt of developing businesses thru environments and experience. Environments and experiences are the only two factors that all businesses have in common, unfortunately 90% of brands are missing one or the other.",
    "cite": "— Rabih Sater",
    "portraitImage": "assets/rabih-sater.png"
  },
  "process": {
    "label": "Engagement",
    "heading": "A structured path<br><em>to transformation.</em>",
    "names": [
      "Discovery &amp; Assessment",
      "Strategy Architecture",
      "Integrated Execution",
      "Measurement &amp; Evolution"
    ],
    "details": [
      "We immerse ourselves in your business before proposing a single solution.",
      "A custom roadmap built around your market, your team, and your ambition.",
      "We work across all five disciplines simultaneously — no siloed thinking.",
      "Every engagement is monitored, refined, and held to results that matter."
    ],
    "pricing": "Engagements from <em>$50,000</em> — structured to the specific needs of your business."
  },
  "contact": {
    "label": "Connect",
    "heading": "Begin your<br><em>engagement.</em>",
    "sub": "We work with a limited number of clients each year. If you are to build something extraordinary, we want to hear from you.",
    "name": "Name",
    "namePh": "Your full name",
    "email": "Email",
    "emailPh": "your@email.com",
    "company": "Company",
    "companyPh": "Company or brand name",
    "message": "Tell us about your vision",
    "messagePh": "Describe your business, your goals, and what you’re looking to achieve.",
    "submit": "Send Enquiry"
  },
  "footer": "© 2026 Method Index, LLC. All Rights Reserved."
};
