const fs   = require('fs');
const path = require('path');

const c = JSON.parse(fs.readFileSync(path.join(__dirname, 'content.json'), 'utf8'));

const serviceNames = c.services.map(function (s) { return s.name; });
const serviceDescs = c.services.map(function (s) { return s.desc; });

const marquee = (serviceNames.join(' &nbsp;·&nbsp; ') + ' &nbsp;·&nbsp; ').repeat(2);

const contentEN = {
  nav: { whatWeDo: 'What', ourStory: 'Who', connect: 'Connect' },
  hero: {
    tagline:         'Built for Those Who Build',
    descHeader:      c.hero.descHeader,
    descBody:        c.hero.descBody,
    backgroundImage: c.hero.backgroundImage
  },
  mission: {
    quote: c.mission.line1 + '<br><em>' + c.mission.line2 + '</em>',
    sub:   c.mission.sub
  },
  whatIntro: {
    heading: c.whatIntro.heading,
    body:    c.whatIntro.body
  },
  services: {
    label:   'What We Do',
    tagline: 'Five disciplines.<br>One integrated approach.',
    names:   serviceNames,
    descs:   serviceDescs,
    marquee: marquee
  },
  about: {
    label:        'Who',
    heading:      c.about.heading1 + '<br><em>' + c.about.heading2 + '</em>',
    body:         c.about.body,
    quote:        c.about.quote,
    cite:         c.about.cite,
    portraitImage: c.about.portraitImage
  },
  process: {
    label:   'Engagement',
    heading: 'A structured path<br><em>to transformation.</em>',
    names:   ['Discovery &amp; Assessment', 'Strategy Architecture', 'Integrated Execution', 'Measurement &amp; Evolution'],
    details: [
      'We immerse ourselves in your business before proposing a single solution.',
      'A custom roadmap built around your market, your team, and your ambition.',
      'We work across all five disciplines simultaneously — no siloed thinking.',
      'Every engagement is monitored, refined, and held to results that matter.'
    ],
    pricing: 'Engagements from <em>$50,000</em> — structured to the specific needs of your business.'
  },
  contact: {
    label:     'Connect',
    heading:   c.contact.heading1 + '<br><em>' + c.contact.heading2 + '</em>',
    sub:       c.contact.sub,
    name:      'Name',    namePh:     'Your full name',
    email:     'Email',   emailPh:    'your@email.com',
    company:   'Company', companyPh:  'Company or brand name',
    message:   'Tell us about your vision',
    messagePh: 'Describe your business, your goals, and what you’re looking to achieve.',
    submit:    'Send Enquiry'
  },
  footer: c.footer
};

const output = '// Auto-generated by build.js — do not edit directly\nvar CONTENT_EN = ' +
  JSON.stringify(contentEN, null, 2) + ';\n';

fs.writeFileSync(path.join(__dirname, 'js', 'content.js'), output);
console.log('✓ js/content.js generated');
